### Traer a todos los animales
GET http://localhost:8000/animals

### Crear un animal
POST http://localhost:8000/animals
Content-Type: application/json

{
	"Nombre": "Santiago",
	"Tipo": "Sapo",
	"Talla": "P",
	"Motivo_ingreso": "Digestion",
	"Edad": 2,
	"Fecha_Ingreso": "2023-10-29T14:32:00.123000",
	"Observacion": "Es ojizarco",
	"Estado": "Ok",
	"Image":"link"
}

###Actualizar un animal
PATCH  http://localhost:8000/animals/652ad177c9934b0e26f6b018
Content-Type: application/json

{
    "Observacion": "Le gusta el pollo y el cerdo"
}

